### ISSUE TITLE
List of contributing companies somewhere relatively visible

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/website-new#11]
@mairin and @lilyx13 In IRC we received a request to add a list somewhere on the site that lists the contributing companies of the project.  I'm not sure how easy or hard that is to do, but I think it would be a nice add if not terribly onerous.

**Comment by mairin** [comment]
@TomSweeneyRedHat that seems reasonable! Do we have a current list somewhere now in git?

**Comment by TomSweeneyRedHat** [comment]
@mairin Probably buried away somewhere, I'll poke around.

**Comment by lilyx13** [comment]
Red Hat, Debian, Suse

- Need to follow up with Suse and Debian on showing them as sponsors. @mairin will follow up with contributors logos being shown.

**Comment by mairin** [comment]
Another: Amadeus

**Comment by mairin** [comment]
(@lilyx13 adding myself as an assignee to make sure i take care of getting the OKs on the logos)

**Comment by lilyx13** [comment]
This shouldn't take long to implement so I'll get it set up at the beginning of next week after I finish up with the dynamic stuff with sprint-4. 

I'll aim to set up the layout so that it'll work with what we have the go ahead to use now, and will have placeholders ready to add the others as they are verified.

**Comment by mairin** [comment]
Here is the current status of approved trademark usages:
white_check_mark Red Hat
white_check_mark Debian (waiting on explicit email approval)
white_check_mark SUSE (as per email to Mo from SUSE)
white_check_mark Amadeus (vrothberg has ok email)
white_check_mark IBM (Mo email to RHT legal)

There are three more that I am working on getting permission for, they need to be left out until / if we get an ok.

**Comment by lilyx13** [comment]
Closed with #28
